version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=semillas_backend

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=semillas_backend
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres

      - mailhog


  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  ejabberd:
    image: rroemhild/ejabberd
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
    environment:
      - ERLANG_NODE=ejabberd
      - XMPP_DOMAIN=semillasocial.org
      - EJABBERD_ADMINS=admin@semillasocial.org
      - EJABBERD_USERS=admin@semillasocial.org:password4321

